### ISSUE TITLE
Mobile Meta

### ISSUE THREAD

**Issue by Mikeysax** [bellvat/Splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by bellvat** [comment]
Hi Michael,
Thank you for reviewing my code. I have added the mobile meta tag, and have committed my latest version. Now the page, mainly the quote, is much easier to read on the mobile page! 

Thanks again, 

Monica

**Comment by Mikeysax** [comment]
:+1:
